version: '3.8'

services:
  webapi:
    build: .
    ports:
      - "8000:80"  # Map port 8000 on the host to port 80 in the container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
